### ISSUE TITLE
Can't get attribute 'SPPF'

### ISSUE THREAD

**Issue by richardgohth** [Chen-MingChang/pytorch_YOLO_OpenVINO_demo#11]
(venv) root@stratton:/pytorch_YOLO_OpenVINO_demo# python3 models/export.py --weights /yolov5/yolov5s/yolov5s.pt --img-size 640
Namespace(batch_size=1, img_size=[640, 640], weights='/yolov5/yolov5s/yolov5s.pt')
Traceback (most recent call last):
  File "models/export.py", line 33, in <module>
    model = attempt_load(opt.weights, map_location=torch.device('cpu'))  # load FP32 model
  File "/pytorch_YOLO_OpenVINO_demo/models/experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/pytorch_YOLO_OpenVINO_demo/venv/lib/python3.7/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/pytorch_YOLO_OpenVINO_demo/venv/lib/python3.7/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/pytorch_YOLO_OpenVINO_demo/venv/lib/python3.7/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/pytorch_YOLO_OpenVINO_demo/models/common.py'>

**Comment by richardgohth** [comment]
after after copy yolov5s.pt from link provided here

**Comment by richardgohth** [comment]
after downloading yolov5s.pt from link provided here.
====
(venv) root@stratton:/pytorch_YOLO_OpenVINO_demo# python models/export.py --weights /syn2/yolov5s.pt  --img-size 640
Namespace(batch_size=1, img_size=[640, 640], weights='/syn2/yolov5s.pt')
Fusing layers... 
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.
Model Summary: 224 layers, 7266973 parameters, 0 gradients

Starting TorchScript export with torch 1.13.1+cu117...
TorchScript export failure: 'Upsample' object has no attribute 'recompute_scale_factor'
ONNX export failure: No module named 'onnx'
